development:
  bucket: 'talott_wpcc_test'
  access_key_id: 'AKIAIJYE5DCLWM432DDQ'
  secret_access_key: '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'

test:
  bucket: 'talott_wpcc_documents'
  access_key_id: 'AKIAIIF64HRN642MBDPA' 
  secret_access_key: '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

production:
  bucket: 'talott_wpcc_documents'
  access_key_id: 'AKIAIIF64HRN642MBDPA' 
  secret_access_key: '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