require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DLoggersController do

  # This should return the minimal set of attributes required to create a valid
  # DLogger. As you add validations to DLogger, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DLoggersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all d_loggers as @d_loggers" do
      d_logger = DLogger.create! valid_attributes
      get :index, {}, valid_session
      assigns(:d_loggers).should eq([d_logger])
    end
  end

  describe "GET show" do
    it "assigns the requested d_logger as @d_logger" do
      d_logger = DLogger.create! valid_attributes
      get :show, {:id => d_logger.to_param}, valid_session
      assigns(:d_logger).should eq(d_logger)
    end
  end

  describe "GET new" do
    it "assigns a new d_logger as @d_logger" do
      get :new, {}, valid_session
      assigns(:d_logger).should be_a_new(DLogger)
    end
  end

  describe "GET edit" do
    it "assigns the requested d_logger as @d_logger" do
      d_logger = DLogger.create! valid_attributes
      get :edit, {:id => d_logger.to_param}, valid_session
      assigns(:d_logger).should eq(d_logger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DLogger" do
        expect {
          post :create, {:d_logger => valid_attributes}, valid_session
        }.to change(DLogger, :count).by(1)
      end

      it "assigns a newly created d_logger as @d_logger" do
        post :create, {:d_logger => valid_attributes}, valid_session
        assigns(:d_logger).should be_a(DLogger)
        assigns(:d_logger).should be_persisted
      end

      it "redirects to the created d_logger" do
        post :create, {:d_logger => valid_attributes}, valid_session
        response.should redirect_to(DLogger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved d_logger as @d_logger" do
        # Trigger the behavior that occurs when invalid params are submitted
        DLogger.any_instance.stub(:save).and_return(false)
        post :create, {:d_logger => {}}, valid_session
        assigns(:d_logger).should be_a_new(DLogger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DLogger.any_instance.stub(:save).and_return(false)
        post :create, {:d_logger => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested d_logger" do
        d_logger = DLogger.create! valid_attributes
        # Assuming there are no other d_loggers in the database, this
        # specifies that the DLogger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DLogger.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => d_logger.to_param, :d_logger => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested d_logger as @d_logger" do
        d_logger = DLogger.create! valid_attributes
        put :update, {:id => d_logger.to_param, :d_logger => valid_attributes}, valid_session
        assigns(:d_logger).should eq(d_logger)
      end

      it "redirects to the d_logger" do
        d_logger = DLogger.create! valid_attributes
        put :update, {:id => d_logger.to_param, :d_logger => valid_attributes}, valid_session
        response.should redirect_to(d_logger)
      end
    end

    describe "with invalid params" do
      it "assigns the d_logger as @d_logger" do
        d_logger = DLogger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DLogger.any_instance.stub(:save).and_return(false)
        put :update, {:id => d_logger.to_param, :d_logger => {}}, valid_session
        assigns(:d_logger).should eq(d_logger)
      end

      it "re-renders the 'edit' template" do
        d_logger = DLogger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DLogger.any_instance.stub(:save).and_return(false)
        put :update, {:id => d_logger.to_param, :d_logger => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested d_logger" do
      d_logger = DLogger.create! valid_attributes
      expect {
        delete :destroy, {:id => d_logger.to_param}, valid_session
      }.to change(DLogger, :count).by(-1)
    end

    it "redirects to the d_loggers list" do
      d_logger = DLogger.create! valid_attributes
      delete :destroy, {:id => d_logger.to_param}, valid_session
      response.should redirect_to(d_loggers_url)
    end
  end

end
