require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostalCodesController do

  # This should return the minimal set of attributes required to create a valid
  # PostalCode. As you add validations to PostalCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostalCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all postal_codes as @postal_codes" do
      postal_code = PostalCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:postal_codes).should eq([postal_code])
    end
  end

  describe "GET show" do
    it "assigns the requested postal_code as @postal_code" do
      postal_code = PostalCode.create! valid_attributes
      get :show, {:id => postal_code.to_param}, valid_session
      assigns(:postal_code).should eq(postal_code)
    end
  end

  describe "GET new" do
    it "assigns a new postal_code as @postal_code" do
      get :new, {}, valid_session
      assigns(:postal_code).should be_a_new(PostalCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested postal_code as @postal_code" do
      postal_code = PostalCode.create! valid_attributes
      get :edit, {:id => postal_code.to_param}, valid_session
      assigns(:postal_code).should eq(postal_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PostalCode" do
        expect {
          post :create, {:postal_code => valid_attributes}, valid_session
        }.to change(PostalCode, :count).by(1)
      end

      it "assigns a newly created postal_code as @postal_code" do
        post :create, {:postal_code => valid_attributes}, valid_session
        assigns(:postal_code).should be_a(PostalCode)
        assigns(:postal_code).should be_persisted
      end

      it "redirects to the created postal_code" do
        post :create, {:postal_code => valid_attributes}, valid_session
        response.should redirect_to(PostalCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved postal_code as @postal_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostalCode.any_instance.stub(:save).and_return(false)
        post :create, {:postal_code => {}}, valid_session
        assigns(:postal_code).should be_a_new(PostalCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostalCode.any_instance.stub(:save).and_return(false)
        post :create, {:postal_code => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested postal_code" do
        postal_code = PostalCode.create! valid_attributes
        # Assuming there are no other postal_codes in the database, this
        # specifies that the PostalCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PostalCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => postal_code.to_param, :postal_code => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested postal_code as @postal_code" do
        postal_code = PostalCode.create! valid_attributes
        put :update, {:id => postal_code.to_param, :postal_code => valid_attributes}, valid_session
        assigns(:postal_code).should eq(postal_code)
      end

      it "redirects to the postal_code" do
        postal_code = PostalCode.create! valid_attributes
        put :update, {:id => postal_code.to_param, :postal_code => valid_attributes}, valid_session
        response.should redirect_to(postal_code)
      end
    end

    describe "with invalid params" do
      it "assigns the postal_code as @postal_code" do
        postal_code = PostalCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostalCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => postal_code.to_param, :postal_code => {}}, valid_session
        assigns(:postal_code).should eq(postal_code)
      end

      it "re-renders the 'edit' template" do
        postal_code = PostalCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostalCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => postal_code.to_param, :postal_code => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested postal_code" do
      postal_code = PostalCode.create! valid_attributes
      expect {
        delete :destroy, {:id => postal_code.to_param}, valid_session
      }.to change(PostalCode, :count).by(-1)
    end

    it "redirects to the postal_codes list" do
      postal_code = PostalCode.create! valid_attributes
      delete :destroy, {:id => postal_code.to_param}, valid_session
      response.should redirect_to(postal_codes_url)
    end
  end

end
